name: deployment.branch.main

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read


jobs:
  test-us-east-1:
    uses: ./.github/workflows/deployment_template.yml
    with:
      region: us-east-1
      account: snowman
      environment: dev