name: Deployment Template

on:
  workflow_call:
    inputs:
      region:
        required: true
        default: us-east-1
        type: string
      account:
        required: true
        type: string
      environment:
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::441058194263:role/amplify_role
          aws-region: us-east-1

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.3.0"

      - name: Install build dependencies
        run: |
            pip install -r requirements-dev.txt

      - name: Install Python dependencies and CDK
        run: |
            pip install -r requirements-dev.txt --target='./amplify_workshop'

      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk@v2.40.0'

      - name: CDK synth
        run: cdk synth
        working-directory: ./amplify_workshop

      - name: CDK deploy
        run: cdk deploy --require-approval never --verbose
        working-directory: ./amplify_workshop